// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

bool validateEmail({required String value}) =>
    RustLib.instance.api.crateApiValidationValidateEmail(value: value);

bool validateUsername({required String value}) =>
    RustLib.instance.api.crateApiValidationValidateUsername(value: value);

bool validatePassword({required String value}) =>
    RustLib.instance.api.crateApiValidationValidatePassword(value: value);
